module.exports.MESSAGES = {
  userNotFound: 'Пользователь с указанным id не найден',
  incorrectData: 'Переданы некорректные данные',
  alreadyExist: 'Данный email уже существует',
  wrongAuthData: 'Неправильные почта или пароль',
  authPassed: 'Авторизация прошла успешно!',
  moviesNotFound: 'Фильм не найден',
  notAllowed: 'Вы не можете удалить этот фильм',
  movieDeleted: 'Фильм успешно удален',
  serverError: 'На сервере произошла ошибка',
  notAuth: 'Пользователь не авторизован',
  cookieRemoved: 'Кукки удалены',
  pageNotFound: 'Страница не найдена',
  wrongUrl: 'Неправильный формат url',
  routNotFound: 'Маршрут не найден',
};
